# `numpy`支持的线性代数运算

In [1]:
#以别名形式导入numpy. 
import numpy as np; 
#导入与ndarray有关的数据类型. 
from numpy import int8, int16, int32, int64; 
from numpy import uint8, uint16, uint32, uint64; 
from numpy import float16, float32, float64; 
from numpy import complex64, complex128; 

In [2]:
#从numpy中单独导入子模块linalg. 
from numpy import linalg as npla; 

## 线性运算
同维向量, 同型矩阵的加法, 数乘

In [3]:
vctA = np.array([1, 0], dtype = float64); 
vctB = np.array([-1, -1], dtype = float64); 

In [4]:
print(vctA + vctB, -2 * vctB); 

[ 0. -1.] [2. 2.]


## 乘法运算

### 向量的数量积
用法: 
```python
v1.dot(v2)
```
其他等效形式
```python
np.dot(v1, v2)
```
`v1`, `v2` 参与数量积运算的向量, 要求
* 均为`np.ndarray`对象
* `ndim`均为`1`, `shape`属性值相同. 


In [5]:
print(np.dot(vctA, vctB)); 

-1.0


### 矩阵的乘法
用法: 
```python
A.dot(B)
```
其他等效形式
```python
np.dot(A, B)
```

`A`, `B` 参与乘法的矩阵, 要求
* 均为`np.ndarray`对象
* `ndim`均为`2`, `A.shape[1] == B.shape[0]`

In [6]:
#定义二维旋转变换矩阵(绕原点旋转)
def rot2D_matrix(rot_angle): 
    cθ = np.cos(rot_angle); sθ = np.sin(rot_angle); 
    ls = [[cθ, -sθ], [sθ, cθ]]; 
    return(np.array(ls, dtype = float64)); 

In [7]:
matA = rot2D_matrix(np.pi / 5); 
matB = rot2D_matrix(- np.pi / 4); 
print(np.dot(matB, matB)); 

[[ 0.  1.]
 [-1.  0.]]


### 矩阵乘法的逆
* 对于非奇异方阵`A`, 使用`np.linalg.inv`求逆. 
```python
np.linalg.inv(A)
```
* 对于行列数不相等的矩阵, 或者奇异方阵`S`, 使用`np.linalg.pinv`求Moore-Penrose广义逆. 
```python
np.linalg.pinv(S)
```
使用`np.linalg.inv`求逆将报错`LinAlgError`

In [8]:
matInvA = npla.inv(matA); 
print(matInvA, rot2D_matrix(- np.pi / 5), sep = "\n\n")

[[ 0.80901699  0.58778525]
 [-0.58778525  0.80901699]]

[[ 0.80901699  0.58778525]
 [-0.58778525  0.80901699]]


### 方阵的幂
用法: 
```python
np.linalg.matrix_power(A, k)
```
* `A` 参与幂运算的方阵, `np.ndarray`对象, 要求`ndim`为`2`, `shape[0] == shape[1]`; 
* `k` 幂指数, `int`对象

In [9]:
#由于numpy.pi不是一个精确值, 因此计算结果在数值上与(- numpy.identity(2))之间存在一定差异. 
print(npla.matrix_power(matInvA, 5)) 

[[-1.00000000e+00 -5.55111512e-17]
 [ 1.11022302e-16 -1.00000000e+00]]


## 初等变换

### 三种初等变换

|初等变换|语句|
|:-:|:-|
|$$r_i \times k$$ $$c_i \times k$$|`A[i, : ] *= k`<br>`A[: , i] *= k`|
|$$r_i + k \cdot r_j$$ $$c_i + k \cdot c_j$$|`A[i, : ] += k * A[j, : ]`<br>`A[: , i] += k * A[: , j]`|
|$$r_i \leftrightarrow r_j$$ $$c_i \leftrightarrow c_j$$|`A[(i, j), : ] = A[(j, i), : ]`<br>`A[: , (i, j)] = A[: , (j, i)]`|

### 行列式与秩
* 对于方阵`A`, 使用`np.linalg.det`求行列式. 
```python
np.linalg.det(A)
```
    对于行列数不相等的矩阵, 使用`np.linalg.det`求行列式将报错`LinAlgError`

* 对于任意形状的矩阵`A`, 使用`np.linalg.matrix_rank`求秩. 
```python
np.linalg.matrix_rank(A)
```

In [10]:
#旋转变换是正交变换, 因此行列式为1. 
#由于numpy.pi不是一个精确值, 因此计算结果在数值上与1之间存在一定差异. 
print(np.linalg.det(matA), np.linalg.det(matB))

1.0000000000000002 1.0
